// Code generated by sszgen. DO NOT EDIT.

//go:build !nosszgen
// +build !nosszgen

package spectests

import "github.com/rjl493456442/sszgen/ssz"

func (obj *AggregateAndProof) SizeSSZ() int {
	size := 12
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	size += obj.Aggregate.SizeSSZ()
	return size
}

func (obj *AggregateAndProof) MarshalSSZTo(w []byte) error {
	_o := 12
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	_o += obj.Aggregate.SizeSSZ()
	ssz.EncodeBytes(w, obj.SelectionProof[:])
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	if err := obj.Aggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *Attestation) SizeSSZ() int {
	size := 36
	size += len(obj.AggregationBits) * 0
	return size
}

func (obj *Attestation) MarshalSSZTo(w []byte) error {
	_o := 36
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.AggregationBits) * 0
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	ssz.EncodeBytes(w, obj.AggregationBits)
	return nil
}

func (obj *AttestationData) SizeSSZ() int {
	size := 32
	return size
}

func (obj *AttestationData) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, uint64(obj.Slot))
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeBytes(w, obj.BeaconBlockHash[:])
	if obj.Source == nil {
		obj.Source = new(Checkpoint)
	}
	if err := obj.Source.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Target == nil {
		obj.Target = new(Checkpoint)
	}
	if err := obj.Target.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *AttesterSlashing) SizeSSZ() int {
	size := 8
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	size += obj.Attestation1.SizeSSZ()
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	size += obj.Attestation2.SizeSSZ()
	return size
}

func (obj *AttesterSlashing) MarshalSSZTo(w []byte) error {
	_o := 8
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	_o += obj.Attestation1.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	_o += obj.Attestation2.SizeSSZ()
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	if err := obj.Attestation1.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	if err := obj.Attestation2.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BLSToExecutionChange) SizeSSZ() int {
	size := 8
	return size
}

func (obj *BLSToExecutionChange) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	ssz.EncodeBytes(w, obj.FromBLSPubKey[:])
	ssz.EncodeBytes(w, obj.ToExecutionAddress[:])
	return nil
}

func (obj *BeaconBlock) SizeSSZ() int {
	size := 20
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	size += obj.Body.SizeSSZ()
	return size
}

func (obj *BeaconBlock) MarshalSSZTo(w []byte) error {
	_o := 20
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	_o += obj.Body.SizeSSZ()
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	if err := obj.Body.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockBodyAltair) SizeSSZ() int {
	size := 28
	size += len(obj.ProposerSlashings) * 32
	for _, _v0 := range obj.AttesterSlashings {
		size += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		size += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		size += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		size += _v1.SizeSSZ()
	}
	size += len(obj.Deposits) * 8
	size += len(obj.VoluntaryExits) * 16
	return size
}

func (obj *BeaconBlockBodyAltair) MarshalSSZTo(w []byte) error {
	_o := 28
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ProposerSlashings) * 32
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v0 := range obj.AttesterSlashings {
		_o += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		_o += _v0.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v1 := range obj.Attestations {
		_o += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		_o += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Deposits) * 8
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.VoluntaryExits) * 16
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v2 := range obj.ProposerSlashings {
		if _v2 == nil {
			_v2 = new(ProposerSlashing)
		}
		if err := _v2.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.AttesterSlashings) * 4
	for _, _v3 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_o))
		if _v3 == nil {
			_v3 = new(AttesterSlashing)
		}
		_o += _v3.SizeSSZ()
	}
	for _, _v4 := range obj.AttesterSlashings {
		if _v4 == nil {
			_v4 = new(AttesterSlashing)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.Attestations) * 4
	for _, _v5 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_o))
		if _v5 == nil {
			_v5 = new(Attestation)
		}
		_o += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.Attestations {
		if _v6 == nil {
			_v6 = new(Attestation)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v7 := range obj.Deposits {
		if _v7 == nil {
			_v7 = new(Deposit)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v8 := range obj.VoluntaryExits {
		if _v8 == nil {
			_v8 = new(SignedVoluntaryExit)
		}
		if err := _v8.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockBodyBellatrix) SizeSSZ() int {
	size := 8
	size += obj.BeaconBlockBodyAltair.SizeSSZ()
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	size += obj.ExecutionPayload.SizeSSZ()
	return size
}

func (obj *BeaconBlockBodyBellatrix) MarshalSSZTo(w []byte) error {
	_o := 8
	ssz.EncodeUint32(w, uint32(_o))
	_o += obj.BeaconBlockBodyAltair.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_o))
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	_o += obj.ExecutionPayload.SizeSSZ()
	if err := obj.BeaconBlockBodyAltair.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	if err := obj.ExecutionPayload.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockBodyCapella) SizeSSZ() int {
	size := 36
	size += len(obj.ProposerSlashings) * 32
	for _, _v0 := range obj.AttesterSlashings {
		size += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		size += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		size += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		size += _v1.SizeSSZ()
	}
	size += len(obj.Deposits) * 8
	size += len(obj.VoluntaryExits) * 16
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	size += obj.ExecutionPayload.SizeSSZ()
	size += len(obj.BlsToExecutionChanges) * 8
	return size
}

func (obj *BeaconBlockBodyCapella) MarshalSSZTo(w []byte) error {
	_o := 36
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ProposerSlashings) * 32
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v0 := range obj.AttesterSlashings {
		_o += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		_o += _v0.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v1 := range obj.Attestations {
		_o += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		_o += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Deposits) * 8
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.VoluntaryExits) * 16
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	_o += obj.ExecutionPayload.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.BlsToExecutionChanges) * 8
	for _, _v2 := range obj.ProposerSlashings {
		if _v2 == nil {
			_v2 = new(ProposerSlashing)
		}
		if err := _v2.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.AttesterSlashings) * 4
	for _, _v3 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_o))
		if _v3 == nil {
			_v3 = new(AttesterSlashing)
		}
		_o += _v3.SizeSSZ()
	}
	for _, _v4 := range obj.AttesterSlashings {
		if _v4 == nil {
			_v4 = new(AttesterSlashing)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.Attestations) * 4
	for _, _v5 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_o))
		if _v5 == nil {
			_v5 = new(Attestation)
		}
		_o += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.Attestations {
		if _v6 == nil {
			_v6 = new(Attestation)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v7 := range obj.Deposits {
		if _v7 == nil {
			_v7 = new(Deposit)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v8 := range obj.VoluntaryExits {
		if _v8 == nil {
			_v8 = new(SignedVoluntaryExit)
		}
		if err := _v8.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	if err := obj.ExecutionPayload.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v9 := range obj.BlsToExecutionChanges {
		if _v9 == nil {
			_v9 = new(SignedBLSToExecutionChange)
		}
		if err := _v9.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockBodyPhase0) SizeSSZ() int {
	size := 28
	size += len(obj.ProposerSlashings) * 32
	for _, _v0 := range obj.AttesterSlashings {
		size += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		size += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		size += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		size += _v1.SizeSSZ()
	}
	size += len(obj.Deposits) * 8
	size += len(obj.VoluntaryExits) * 16
	return size
}

func (obj *BeaconBlockBodyPhase0) MarshalSSZTo(w []byte) error {
	_o := 28
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ProposerSlashings) * 32
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v0 := range obj.AttesterSlashings {
		_o += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		_o += _v0.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v1 := range obj.Attestations {
		_o += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		_o += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Deposits) * 8
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.VoluntaryExits) * 16
	for _, _v2 := range obj.ProposerSlashings {
		if _v2 == nil {
			_v2 = new(ProposerSlashing)
		}
		if err := _v2.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.AttesterSlashings) * 4
	for _, _v3 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_o))
		if _v3 == nil {
			_v3 = new(AttesterSlashing)
		}
		_o += _v3.SizeSSZ()
	}
	for _, _v4 := range obj.AttesterSlashings {
		if _v4 == nil {
			_v4 = new(AttesterSlashing)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.Attestations) * 4
	for _, _v5 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_o))
		if _v5 == nil {
			_v5 = new(Attestation)
		}
		_o += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.Attestations {
		if _v6 == nil {
			_v6 = new(Attestation)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v7 := range obj.Deposits {
		if _v7 == nil {
			_v7 = new(Deposit)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v8 := range obj.VoluntaryExits {
		if _v8 == nil {
			_v8 = new(SignedVoluntaryExit)
		}
		if err := _v8.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockCapella) SizeSSZ() int {
	size := 20
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	size += obj.Body.SizeSSZ()
	return size
}

func (obj *BeaconBlockCapella) MarshalSSZTo(w []byte) error {
	_o := 20
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	_o += obj.Body.SizeSSZ()
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	if err := obj.Body.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockHeader) SizeSSZ() int {
	size := 16
	return size
}

func (obj *BeaconBlockHeader) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeBytes(w, obj.BodyRoot)
	return nil
}

func (obj *BeaconState) SizeSSZ() int {
	size := 65640
	size += len(obj.HistoricalRoots) * 0
	size += len(obj.Eth1DataVotes) * 8
	size += len(obj.Validators) * 41
	size += len(obj.Balances) * 8
	for _, _v0 := range obj.PreviousEpochAttestations {
		size += 4
		if _v0 == nil {
			_v0 = new(PendingAttestation)
		}
		size += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.CurrentEpochAttestations {
		size += 4
		if _v1 == nil {
			_v1 = new(PendingAttestation)
		}
		size += _v1.SizeSSZ()
	}
	return size
}

func (obj *BeaconState) MarshalSSZTo(w []byte) error {
	_o := 65640
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0)
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1)
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.HistoricalRoots) * 0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Eth1DataVotes) * 8
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Validators) * 41
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Balances) * 8
	for _, _v2 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v3 := range obj.PreviousEpochAttestations {
		_o += 4
		if _v3 == nil {
			_v3 = new(PendingAttestation)
		}
		_o += _v3.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v4 := range obj.CurrentEpochAttestations {
		_o += 4
		if _v4 == nil {
			_v4 = new(PendingAttestation)
		}
		_o += _v4.SizeSSZ()
	}
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v5 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v5)
	}
	for _, _v6 := range obj.Eth1DataVotes {
		if _v6 == nil {
			_v6 = new(Eth1Data)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v7 := range obj.Validators {
		if _v7 == nil {
			_v7 = new(Validator)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	_o = len(obj.PreviousEpochAttestations) * 4
	for _, _v8 := range obj.PreviousEpochAttestations {
		ssz.EncodeUint32(w, uint32(_o))
		if _v8 == nil {
			_v8 = new(PendingAttestation)
		}
		_o += _v8.SizeSSZ()
	}
	for _, _v9 := range obj.PreviousEpochAttestations {
		if _v9 == nil {
			_v9 = new(PendingAttestation)
		}
		if err := _v9.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_o = len(obj.CurrentEpochAttestations) * 4
	for _, _v10 := range obj.CurrentEpochAttestations {
		ssz.EncodeUint32(w, uint32(_o))
		if _v10 == nil {
			_v10 = new(PendingAttestation)
		}
		_o += _v10.SizeSSZ()
	}
	for _, _v11 := range obj.CurrentEpochAttestations {
		if _v11 == nil {
			_v11 = new(PendingAttestation)
		}
		if err := _v11.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconStateAltair) SizeSSZ() int {
	size := 65644
	size += len(obj.HistoricalRoots) * 0
	size += len(obj.Eth1DataVotes) * 8
	size += len(obj.Validators) * 41
	size += len(obj.Balances) * 8
	size += len(obj.PreviousEpochParticipation) * 0
	size += len(obj.CurrentEpochParticipation) * 0
	size += len(obj.InactivityScores) * 8
	return size
}

func (obj *BeaconStateAltair) MarshalSSZTo(w []byte) error {
	_o := 65644
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0)
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1)
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.HistoricalRoots) * 0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Eth1DataVotes) * 8
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Validators) * 41
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Balances) * 8
	for _, _v2 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.PreviousEpochParticipation) * 0
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.CurrentEpochParticipation) * 0
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v3 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v3)
	}
	for _, _v4 := range obj.Eth1DataVotes {
		if _v4 == nil {
			_v4 = new(Eth1Data)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v5 := range obj.Validators {
		if _v5 == nil {
			_v5 = new(Validator)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	return nil
}

func (obj *BeaconStateBellatrix) SizeSSZ() int {
	size := 65648
	size += len(obj.HistoricalRoots) * 0
	size += len(obj.Eth1DataVotes) * 8
	size += len(obj.Validators) * 41
	size += len(obj.Balances) * 8
	size += len(obj.PreviousEpochParticipation) * 0
	size += len(obj.CurrentEpochParticipation) * 0
	size += len(obj.InactivityScores) * 8
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	size += obj.LatestExecutionPayloadHeader.SizeSSZ()
	return size
}

func (obj *BeaconStateBellatrix) MarshalSSZTo(w []byte) error {
	_o := 65648
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0)
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1)
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.HistoricalRoots) * 0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Eth1DataVotes) * 8
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Validators) * 41
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Balances) * 8
	for _, _v2 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.PreviousEpochParticipation) * 0
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.CurrentEpochParticipation) * 0
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	_o += obj.LatestExecutionPayloadHeader.SizeSSZ()
	for _, _v3 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v3)
	}
	for _, _v4 := range obj.Eth1DataVotes {
		if _v4 == nil {
			_v4 = new(Eth1Data)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v5 := range obj.Validators {
		if _v5 == nil {
			_v5 = new(Validator)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	if err := obj.LatestExecutionPayloadHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconStateCapella) SizeSSZ() int {
	size := 65668
	size += len(obj.HistoricalRoots) * 0
	size += len(obj.Eth1DataVotes) * 8
	size += len(obj.Validators) * 41
	size += len(obj.Balances) * 8
	size += len(obj.PreviousEpochParticipation) * 0
	size += len(obj.CurrentEpochParticipation) * 0
	size += len(obj.InactivityScores) * 8
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	size += obj.LatestExecutionPayloadHeader.SizeSSZ()
	size += len(obj.HistoricalSummaries) * 0
	return size
}

func (obj *BeaconStateCapella) MarshalSSZTo(w []byte) error {
	_o := 65668
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot[:])
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0[:])
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1[:])
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.HistoricalRoots) * 0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Eth1DataVotes) * 8
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Validators) * 41
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Balances) * 8
	for _, _v2 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v2[:])
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.PreviousEpochParticipation) * 0
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.CurrentEpochParticipation) * 0
	ssz.EncodeBytes(w, obj.JustificationBits[:])
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_o))
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	_o += obj.LatestExecutionPayloadHeader.SizeSSZ()
	ssz.EncodeUint64(w, obj.NextWithdrawalIndex)
	ssz.EncodeUint64(w, obj.NextWithdrawalValidatorIndex)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.HistoricalSummaries) * 0
	for _, _v3 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v3)
	}
	for _, _v4 := range obj.Eth1DataVotes {
		if _v4 == nil {
			_v4 = new(Eth1Data)
		}
		if err := _v4.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v5 := range obj.Validators {
		if _v5 == nil {
			_v5 = new(Validator)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	if err := obj.LatestExecutionPayloadHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v6 := range obj.HistoricalSummaries {
		if _v6 == nil {
			_v6 = new(HistoricalSummary)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *Checkpoint) SizeSSZ() int {
	size := 8
	return size
}

func (obj *Checkpoint) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Epoch)
	ssz.EncodeBytes(w, obj.Root)
	return nil
}

func (obj *Deposit) SizeSSZ() int {
	size := 8
	return size
}

func (obj *Deposit) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.Proof {
		ssz.EncodeBytes(w, _v0)
	}
	if obj.Data == nil {
		obj.Data = new(DepositData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *DepositData) SizeSSZ() int {
	size := 8
	return size
}

func (obj *DepositData) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey[:])
	ssz.EncodeBytes(w, obj.WithdrawalCredentials[:])
	ssz.EncodeUint64(w, obj.Amount)
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *DepositMessage) SizeSSZ() int {
	size := 8
	return size
}

func (obj *DepositMessage) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.WithdrawalCredentials)
	ssz.EncodeUint64(w, obj.Amount)
	return nil
}

func (obj *ErrorResponse) SizeSSZ() int {
	size := 4
	size += len(obj.Message) * 0
	return size
}

func (obj *ErrorResponse) MarshalSSZTo(w []byte) error {
	_o := 4
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Message) * 0
	ssz.EncodeBytes(w, obj.Message)
	return nil
}

func (obj *Eth1Block) SizeSSZ() int {
	size := 16
	return size
}

func (obj *Eth1Block) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeBytes(w, obj.DepositRoot)
	ssz.EncodeUint64(w, obj.DepositCount)
	return nil
}

func (obj *Eth1Data) SizeSSZ() int {
	size := 8
	return size
}

func (obj *Eth1Data) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.DepositRoot)
	ssz.EncodeUint64(w, obj.DepositCount)
	ssz.EncodeBytes(w, obj.BlockHash)
	return nil
}

func (obj *ExecutionPayload) SizeSSZ() int {
	size := 40
	size += len(obj.ExtraData) * 0
	for _, _v0 := range obj.Transactions {
		size += 4
		size += len(_v0) * 0
	}
	return size
}

func (obj *ExecutionPayload) MarshalSSZTo(w []byte) error {
	_o := 40
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ExtraData) * 0
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v0 := range obj.Transactions {
		_o += 4
		_o += len(_v0) * 0
	}
	ssz.EncodeBytes(w, obj.ExtraData)
	_o = len(obj.Transactions) * 4
	for _, _v1 := range obj.Transactions {
		ssz.EncodeUint32(w, uint32(_o))
		_o += len(_v1) * 0
	}
	for _, _v2 := range obj.Transactions {
		ssz.EncodeBytes(w, _v2)
	}
	return nil
}

func (obj *ExecutionPayloadCapella) SizeSSZ() int {
	size := 44
	size += len(obj.ExtraData) * 0
	for _, _v0 := range obj.Transactions {
		size += 4
		size += len(_v0) * 0
	}
	size += len(obj.Withdrawals) * 24
	return size
}

func (obj *ExecutionPayloadCapella) MarshalSSZTo(w []byte) error {
	_o := 44
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ExtraData) * 0
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeUint32(w, uint32(_o))
	for _, _v0 := range obj.Transactions {
		_o += 4
		_o += len(_v0) * 0
	}
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.Withdrawals) * 24
	ssz.EncodeBytes(w, obj.ExtraData)
	_o = len(obj.Transactions) * 4
	for _, _v1 := range obj.Transactions {
		ssz.EncodeUint32(w, uint32(_o))
		_o += len(_v1) * 0
	}
	for _, _v2 := range obj.Transactions {
		ssz.EncodeBytes(w, _v2)
	}
	for _, _v3 := range obj.Withdrawals {
		if _v3 == nil {
			_v3 = new(Withdrawal)
		}
		if err := _v3.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *ExecutionPayloadHeader) SizeSSZ() int {
	size := 36
	size += len(obj.ExtraData) * 0
	return size
}

func (obj *ExecutionPayloadHeader) MarshalSSZTo(w []byte) error {
	_o := 36
	ssz.EncodeBytes(w, obj.ParentHash)
	ssz.EncodeBytes(w, obj.FeeRecipient)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeBytes(w, obj.ReceiptsRoot)
	ssz.EncodeBytes(w, obj.LogsBloom)
	ssz.EncodeBytes(w, obj.PrevRandao)
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ExtraData) * 0
	ssz.EncodeBytes(w, obj.BaseFeePerGas)
	ssz.EncodeBytes(w, obj.BlockHash)
	ssz.EncodeBytes(w, obj.TransactionsRoot)
	ssz.EncodeBytes(w, obj.ExtraData)
	return nil
}

func (obj *ExecutionPayloadHeaderCapella) SizeSSZ() int {
	size := 36
	size += len(obj.ExtraData) * 0
	return size
}

func (obj *ExecutionPayloadHeaderCapella) MarshalSSZTo(w []byte) error {
	_o := 36
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.ExtraData) * 0
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeBytes(w, obj.TransactionsRoot[:])
	ssz.EncodeBytes(w, obj.WithdrawalRoot[:])
	ssz.EncodeBytes(w, obj.ExtraData)
	return nil
}

func (obj *Fork) SizeSSZ() int {
	size := 8
	return size
}

func (obj *Fork) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.PreviousVersion)
	ssz.EncodeBytes(w, obj.CurrentVersion)
	ssz.EncodeUint64(w, obj.Epoch)
	return nil
}

func (obj *HistoricalBatch) SizeSSZ() int {
	size := 0
	return size
}

func (obj *HistoricalBatch) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0[:])
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1[:])
	}
	return nil
}

func (obj *HistoricalSummary) SizeSSZ() int {
	size := 0
	return size
}

func (obj *HistoricalSummary) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.BlockSummaryRoot[:])
	ssz.EncodeBytes(w, obj.StateSummaryRoot[:])
	return nil
}

func (obj *IndexedAttestation) SizeSSZ() int {
	size := 36
	size += len(obj.AttestationIndices) * 8
	return size
}

func (obj *IndexedAttestation) MarshalSSZTo(w []byte) error {
	_o := 36
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.AttestationIndices) * 8
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature)
	ssz.EncodeUint64s(w, obj.AttestationIndices)
	return nil
}

func (obj *PendingAttestation) SizeSSZ() int {
	size := 52
	size += len(obj.AggregationBits) * 0
	return size
}

func (obj *PendingAttestation) MarshalSSZTo(w []byte) error {
	_o := 52
	ssz.EncodeUint32(w, uint32(_o))
	_o += len(obj.AggregationBits) * 0
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint64(w, obj.InclusionDelay)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.AggregationBits)
	return nil
}

func (obj *ProposerSlashing) SizeSSZ() int {
	size := 32
	return size
}

func (obj *ProposerSlashing) MarshalSSZTo(w []byte) error {
	if obj.Header1 == nil {
		obj.Header1 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header1.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Header2 == nil {
		obj.Header2 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header2.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBLSToExecutionChange) SizeSSZ() int {
	size := 8
	return size
}

func (obj *SignedBLSToExecutionChange) MarshalSSZTo(w []byte) error {
	if obj.Message == nil {
		obj.Message = new(BLSToExecutionChange)
	}
	if err := obj.Message.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	return nil
}

func (obj *SignedBeaconBlock) SizeSSZ() int {
	size := 4
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	size += obj.Block.SizeSSZ()
	return size
}

func (obj *SignedBeaconBlock) MarshalSSZTo(w []byte) error {
	_o := 4
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	_o += obj.Block.SizeSSZ()
	ssz.EncodeBytes(w, obj.Signature)
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	if err := obj.Block.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlockCapella) SizeSSZ() int {
	size := 4
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	size += obj.Block.SizeSSZ()
	return size
}

func (obj *SignedBeaconBlockCapella) MarshalSSZTo(w []byte) error {
	_o := 4
	ssz.EncodeUint32(w, uint32(_o))
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	_o += obj.Block.SizeSSZ()
	ssz.EncodeBytes(w, obj.Signature)
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	if err := obj.Block.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlockHeader) SizeSSZ() int {
	size := 16
	return size
}

func (obj *SignedBeaconBlockHeader) MarshalSSZTo(w []byte) error {
	if obj.Header == nil {
		obj.Header = new(BeaconBlockHeader)
	}
	if err := obj.Header.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *SignedVoluntaryExit) SizeSSZ() int {
	size := 16
	return size
}

func (obj *SignedVoluntaryExit) MarshalSSZTo(w []byte) error {
	if obj.Exit == nil {
		obj.Exit = new(VoluntaryExit)
	}
	if err := obj.Exit.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	return nil
}

func (obj *SigningRoot) SizeSSZ() int {
	size := 0
	return size
}

func (obj *SigningRoot) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.ObjectRoot)
	ssz.EncodeBytes(w, obj.Domain)
	return nil
}

func (obj *SyncAggregate) SizeSSZ() int {
	size := 0
	return size
}

func (obj *SyncAggregate) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.SyncCommiteeBits)
	ssz.EncodeBytes(w, obj.SyncCommiteeSignature[:])
	return nil
}

func (obj *SyncCommittee) SizeSSZ() int {
	size := 0
	return size
}

func (obj *SyncCommittee) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.PubKeys {
		ssz.EncodeBytes(w, _v0)
	}
	ssz.EncodeBytes(w, obj.AggregatePubKey[:])
	return nil
}

func (obj *Transfer) SizeSSZ() int {
	size := 40
	return size
}

func (obj *Transfer) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Sender)
	ssz.EncodeUint64(w, obj.Recipient)
	ssz.EncodeUint64(w, obj.Amount)
	ssz.EncodeUint64(w, obj.Fee)
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *Validator) SizeSSZ() int {
	size := 41
	return size
}

func (obj *Validator) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.WithdrawalCredentials)
	ssz.EncodeUint64(w, obj.EffectiveBalance)
	ssz.EncodeBool(w, obj.Slashed)
	ssz.EncodeUint64(w, obj.ActivationEligibilityEpoch)
	ssz.EncodeUint64(w, obj.ActivationEpoch)
	ssz.EncodeUint64(w, obj.ExitEpoch)
	ssz.EncodeUint64(w, obj.WithdrawableEpoch)
	return nil
}

func (obj *VoluntaryExit) SizeSSZ() int {
	size := 16
	return size
}

func (obj *VoluntaryExit) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Epoch)
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	return nil
}

func (obj *Withdrawal) SizeSSZ() int {
	size := 24
	return size
}

func (obj *Withdrawal) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	ssz.EncodeBytes(w, obj.Address[:])
	ssz.EncodeUint64(w, obj.Amount)
	return nil
}
