// Code generated by sszgen. DO NOT EDIT.

//go:build !nosszgen
// +build !nosszgen

package spectests

import "github.com/rjl493456442/sszgen/ssz"

func (obj *AggregateAndProof) SizeSSZ() int {
	s := 108
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	s += obj.Aggregate.SizeSSZ()
	return s
}

func (obj *AggregateAndProof) MarshalSSZTo(w []byte) error {
	_v0 := 108
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	_v0 += obj.Aggregate.SizeSSZ()
	ssz.EncodeBytes(w, obj.SelectionProof[:])
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	if err := obj.Aggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *AggregateAndProof) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Index = _v0
	r, _v1, _e1 := ssz.DecodeUint32(r)
	if _e1 != nil {
		return _e1
	}
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.SelectionProof = _v2
	_v3 := r[_v1:]
	if obj.Aggregate == nil {
		obj.Aggregate = new(Attestation)
	}
	if err := obj.Aggregate.UnmarshalSSZ(_v3); err != nil {
		return err
	}
	return nil
}

func (obj *Attestation) SizeSSZ() int {
	s := 228
	s += len(obj.AggregationBits)
	return s
}

func (obj *Attestation) MarshalSSZTo(w []byte) error {
	_v0 := 228
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.AggregationBits)
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	ssz.EncodeBytes(w, obj.AggregationBits)
	return nil
}

func (obj *Attestation) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Signature = _v1
	_v2 := r[_v0:]
	_v2, _v3, _e2 := ssz.DecodeBytes(_v2)
	if _e2 != nil {
		return _e2
	}
	obj.AggregationBits = _v3
	return nil
}

func (obj *AttestationData) SizeSSZ() int {
	s := 128
	return s
}

func (obj *AttestationData) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, uint64(obj.Slot))
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeBytes(w, obj.BeaconBlockHash[:])
	if obj.Source == nil {
		obj.Source = new(Checkpoint)
	}
	if err := obj.Source.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Target == nil {
		obj.Target = new(Checkpoint)
	}
	if err := obj.Target.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *AttestationData) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Slot = Slot(_v0)
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.Index = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.BeaconBlockHash = _v2
	if obj.Source == nil {
		obj.Source = new(Checkpoint)
	}
	if err := obj.Source.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.Target == nil {
		obj.Target = new(Checkpoint)
	}
	if err := obj.Target.UnmarshalSSZ(r); err != nil {
		return err
	}
	return nil
}

func (obj *AttesterSlashing) SizeSSZ() int {
	s := 8
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	s += obj.Attestation1.SizeSSZ()
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	s += obj.Attestation2.SizeSSZ()
	return s
}

func (obj *AttesterSlashing) MarshalSSZTo(w []byte) error {
	_v0 := 8
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	_v0 += obj.Attestation1.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	_v0 += obj.Attestation2.SizeSSZ()
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	if err := obj.Attestation1.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	if err := obj.Attestation2.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *AttesterSlashing) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	r, _v1, _e1 := ssz.DecodeUint32(r)
	if _e1 != nil {
		return _e1
	}
	_v2 := r[_v0:_v1]
	if obj.Attestation1 == nil {
		obj.Attestation1 = new(IndexedAttestation)
	}
	if err := obj.Attestation1.UnmarshalSSZ(_v2); err != nil {
		return err
	}
	_v3 := r[_v0:_v1]
	if obj.Attestation2 == nil {
		obj.Attestation2 = new(IndexedAttestation)
	}
	if err := obj.Attestation2.UnmarshalSSZ(_v3); err != nil {
		return err
	}
	return nil
}

func (obj *BLSToExecutionChange) SizeSSZ() int {
	s := 76
	return s
}

func (obj *BLSToExecutionChange) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	ssz.EncodeBytes(w, obj.FromBLSPubKey[:])
	ssz.EncodeBytes(w, obj.ToExecutionAddress[:])
	return nil
}

func (obj *BLSToExecutionChange) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.ValidatorIndex = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.FromBLSPubKey = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.ToExecutionAddress = _v2
	return nil
}

func (obj *BeaconBlock) SizeSSZ() int {
	s := 84
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	s += obj.Body.SizeSSZ()
	return s
}

func (obj *BeaconBlock) MarshalSSZTo(w []byte) error {
	_v0 := 84
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	_v0 += obj.Body.SizeSSZ()
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	if err := obj.Body.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlock) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Slot = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.ProposerIndex = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.ParentRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.StateRoot = _v3
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	_v5 := r[_v4:]
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyPhase0)
	}
	if err := obj.Body.UnmarshalSSZ(_v5); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockBodyAltair) SizeSSZ() int {
	s := 380
	s += len(obj.ProposerSlashings) * 416
	for _, _v0 := range obj.AttesterSlashings {
		s += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		s += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		s += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		s += _v1.SizeSSZ()
	}
	s += len(obj.Deposits) * 1240
	s += len(obj.VoluntaryExits) * 112
	return s
}

func (obj *BeaconBlockBodyAltair) MarshalSSZTo(w []byte) error {
	_v0 := 380
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ProposerSlashings) * 416
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v1 := range obj.AttesterSlashings {
		_v0 += 4
		if _v1 == nil {
			_v1 = new(AttesterSlashing)
		}
		_v0 += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v2 := range obj.Attestations {
		_v0 += 4
		if _v2 == nil {
			_v2 = new(Attestation)
		}
		_v0 += _v2.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Deposits) * 1240
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.VoluntaryExits) * 112
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v3 := range obj.ProposerSlashings {
		if _v3 == nil {
			_v3 = new(ProposerSlashing)
		}
		if err := _v3.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v4 := len(obj.AttesterSlashings) * 4
	for _, _v5 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_v4))
		if _v5 == nil {
			_v5 = new(AttesterSlashing)
		}
		_v4 += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.AttesterSlashings {
		if _v6 == nil {
			_v6 = new(AttesterSlashing)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v7 := len(obj.Attestations) * 4
	for _, _v8 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_v7))
		if _v8 == nil {
			_v8 = new(Attestation)
		}
		_v7 += _v8.SizeSSZ()
	}
	for _, _v9 := range obj.Attestations {
		if _v9 == nil {
			_v9 = new(Attestation)
		}
		if err := _v9.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v10 := range obj.Deposits {
		if _v10 == nil {
			_v10 = new(Deposit)
		}
		if err := _v10.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v11 := range obj.VoluntaryExits {
		if _v11 == nil {
			_v11 = new(SignedVoluntaryExit)
		}
		if err := _v11.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockBodyAltair) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.RandaoReveal = _v0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Graffiti = _v1
	r, _v2, _e2 := ssz.DecodeUint32(r)
	if _e2 != nil {
		return _e2
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint32(r)
	if _e5 != nil {
		return _e5
	}
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.UnmarshalSSZ(r); err != nil {
		return err
	}
	_v7 := r[_v2:_v3]
	_v8 := r[_v2:_v3]
	_v9 := r[_v2:_v3]
	_v10 := r[_v2:_v3]
	_v11 := r[_v2:_v3]
	return nil
}

func (obj *BeaconBlockBodyBellatrix) SizeSSZ() int {
	s := 8
	s += obj.BeaconBlockBodyAltair.SizeSSZ()
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	s += obj.ExecutionPayload.SizeSSZ()
	return s
}

func (obj *BeaconBlockBodyBellatrix) MarshalSSZTo(w []byte) error {
	_v0 := 8
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += obj.BeaconBlockBodyAltair.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	_v0 += obj.ExecutionPayload.SizeSSZ()
	if err := obj.BeaconBlockBodyAltair.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	if err := obj.ExecutionPayload.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockBodyBellatrix) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	r, _v1, _e1 := ssz.DecodeUint32(r)
	if _e1 != nil {
		return _e1
	}
	_v2 := r[_v0:_v1]
	if err := obj.BeaconBlockBodyAltair.UnmarshalSSZ(_v2); err != nil {
		return err
	}
	_v3 := r[_v0:_v1]
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayload)
	}
	if err := obj.ExecutionPayload.UnmarshalSSZ(_v3); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockBodyCapella) SizeSSZ() int {
	s := 388
	s += len(obj.ProposerSlashings) * 416
	for _, _v0 := range obj.AttesterSlashings {
		s += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		s += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		s += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		s += _v1.SizeSSZ()
	}
	s += len(obj.Deposits) * 1240
	s += len(obj.VoluntaryExits) * 112
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	s += obj.ExecutionPayload.SizeSSZ()
	s += len(obj.BlsToExecutionChanges) * 172
	return s
}

func (obj *BeaconBlockBodyCapella) MarshalSSZTo(w []byte) error {
	_v0 := 388
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ProposerSlashings) * 416
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v1 := range obj.AttesterSlashings {
		_v0 += 4
		if _v1 == nil {
			_v1 = new(AttesterSlashing)
		}
		_v0 += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v2 := range obj.Attestations {
		_v0 += 4
		if _v2 == nil {
			_v2 = new(Attestation)
		}
		_v0 += _v2.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Deposits) * 1240
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.VoluntaryExits) * 112
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	_v0 += obj.ExecutionPayload.SizeSSZ()
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.BlsToExecutionChanges) * 172
	for _, _v3 := range obj.ProposerSlashings {
		if _v3 == nil {
			_v3 = new(ProposerSlashing)
		}
		if err := _v3.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v4 := len(obj.AttesterSlashings) * 4
	for _, _v5 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_v4))
		if _v5 == nil {
			_v5 = new(AttesterSlashing)
		}
		_v4 += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.AttesterSlashings {
		if _v6 == nil {
			_v6 = new(AttesterSlashing)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v7 := len(obj.Attestations) * 4
	for _, _v8 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_v7))
		if _v8 == nil {
			_v8 = new(Attestation)
		}
		_v7 += _v8.SizeSSZ()
	}
	for _, _v9 := range obj.Attestations {
		if _v9 == nil {
			_v9 = new(Attestation)
		}
		if err := _v9.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v10 := range obj.Deposits {
		if _v10 == nil {
			_v10 = new(Deposit)
		}
		if err := _v10.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v11 := range obj.VoluntaryExits {
		if _v11 == nil {
			_v11 = new(SignedVoluntaryExit)
		}
		if err := _v11.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	if err := obj.ExecutionPayload.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v12 := range obj.BlsToExecutionChanges {
		if _v12 == nil {
			_v12 = new(SignedBLSToExecutionChange)
		}
		if err := _v12.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockBodyCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.RandaoReveal = _v0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Graffiti = _v1
	r, _v2, _e2 := ssz.DecodeUint32(r)
	if _e2 != nil {
		return _e2
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint32(r)
	if _e5 != nil {
		return _e5
	}
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	if obj.SyncAggregate == nil {
		obj.SyncAggregate = new(SyncAggregate)
	}
	if err := obj.SyncAggregate.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v7, _e7 := ssz.DecodeUint32(r)
	if _e7 != nil {
		return _e7
	}
	r, _v8, _e8 := ssz.DecodeUint32(r)
	if _e8 != nil {
		return _e8
	}
	_v9 := r[_v2:_v3]
	_v10 := r[_v2:_v3]
	_v11 := r[_v2:_v3]
	_v12 := r[_v2:_v3]
	_v13 := r[_v2:_v3]
	_v14 := r[_v2:_v3]
	if obj.ExecutionPayload == nil {
		obj.ExecutionPayload = new(ExecutionPayloadCapella)
	}
	if err := obj.ExecutionPayload.UnmarshalSSZ(_v14); err != nil {
		return err
	}
	_v15 := r[_v2:_v3]
	return nil
}

func (obj *BeaconBlockBodyPhase0) SizeSSZ() int {
	s := 220
	s += len(obj.ProposerSlashings) * 416
	for _, _v0 := range obj.AttesterSlashings {
		s += 4
		if _v0 == nil {
			_v0 = new(AttesterSlashing)
		}
		s += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.Attestations {
		s += 4
		if _v1 == nil {
			_v1 = new(Attestation)
		}
		s += _v1.SizeSSZ()
	}
	s += len(obj.Deposits) * 1240
	s += len(obj.VoluntaryExits) * 112
	return s
}

func (obj *BeaconBlockBodyPhase0) MarshalSSZTo(w []byte) error {
	_v0 := 220
	ssz.EncodeBytes(w, obj.RandaoReveal)
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Graffiti[:])
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ProposerSlashings) * 416
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v1 := range obj.AttesterSlashings {
		_v0 += 4
		if _v1 == nil {
			_v1 = new(AttesterSlashing)
		}
		_v0 += _v1.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v2 := range obj.Attestations {
		_v0 += 4
		if _v2 == nil {
			_v2 = new(Attestation)
		}
		_v0 += _v2.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Deposits) * 1240
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.VoluntaryExits) * 112
	for _, _v3 := range obj.ProposerSlashings {
		if _v3 == nil {
			_v3 = new(ProposerSlashing)
		}
		if err := _v3.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v4 := len(obj.AttesterSlashings) * 4
	for _, _v5 := range obj.AttesterSlashings {
		ssz.EncodeUint32(w, uint32(_v4))
		if _v5 == nil {
			_v5 = new(AttesterSlashing)
		}
		_v4 += _v5.SizeSSZ()
	}
	for _, _v6 := range obj.AttesterSlashings {
		if _v6 == nil {
			_v6 = new(AttesterSlashing)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v7 := len(obj.Attestations) * 4
	for _, _v8 := range obj.Attestations {
		ssz.EncodeUint32(w, uint32(_v7))
		if _v8 == nil {
			_v8 = new(Attestation)
		}
		_v7 += _v8.SizeSSZ()
	}
	for _, _v9 := range obj.Attestations {
		if _v9 == nil {
			_v9 = new(Attestation)
		}
		if err := _v9.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v10 := range obj.Deposits {
		if _v10 == nil {
			_v10 = new(Deposit)
		}
		if err := _v10.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v11 := range obj.VoluntaryExits {
		if _v11 == nil {
			_v11 = new(SignedVoluntaryExit)
		}
		if err := _v11.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconBlockBodyPhase0) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.RandaoReveal = _v0
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Graffiti = _v1
	r, _v2, _e2 := ssz.DecodeUint32(r)
	if _e2 != nil {
		return _e2
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint32(r)
	if _e5 != nil {
		return _e5
	}
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	_v7 := r[_v2:_v3]
	_v8 := r[_v2:_v3]
	_v9 := r[_v2:_v3]
	_v10 := r[_v2:_v3]
	_v11 := r[_v2:_v3]
	return nil
}

func (obj *BeaconBlockCapella) SizeSSZ() int {
	s := 84
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	s += obj.Body.SizeSSZ()
	return s
}

func (obj *BeaconBlockCapella) MarshalSSZTo(w []byte) error {
	_v0 := 84
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	_v0 += obj.Body.SizeSSZ()
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	if err := obj.Body.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Slot = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.ProposerIndex = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.ParentRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.StateRoot = _v3
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	_v5 := r[_v4:]
	if obj.Body == nil {
		obj.Body = new(BeaconBlockBodyCapella)
	}
	if err := obj.Body.UnmarshalSSZ(_v5); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconBlockHeader) SizeSSZ() int {
	s := 112
	return s
}

func (obj *BeaconBlockHeader) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.ParentRoot)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeBytes(w, obj.BodyRoot)
	return nil
}

func (obj *BeaconBlockHeader) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Slot = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.ProposerIndex = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.ParentRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.StateRoot = _v3
	r, _v4, _e4 := ssz.DecodeBytes(r)
	if _e4 != nil {
		return _e4
	}
	obj.BodyRoot = _v4
	return nil
}

func (obj *BeaconState) SizeSSZ() int {
	s := 2687377
	s += len(obj.HistoricalRoots) * 32
	s += len(obj.Eth1DataVotes) * 72
	s += len(obj.Validators) * 121
	s += len(obj.Balances) * 8
	for _, _v0 := range obj.PreviousEpochAttestations {
		s += 4
		if _v0 == nil {
			_v0 = new(PendingAttestation)
		}
		s += _v0.SizeSSZ()
	}
	for _, _v1 := range obj.CurrentEpochAttestations {
		s += 4
		if _v1 == nil {
			_v1 = new(PendingAttestation)
		}
		s += _v1.SizeSSZ()
	}
	return s
}

func (obj *BeaconState) MarshalSSZTo(w []byte) error {
	_v0 := 2687377
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v1 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v1)
	}
	for _, _v2 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.HistoricalRoots) * 32
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Eth1DataVotes) * 72
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Validators) * 121
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Balances) * 8
	for _, _v3 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v3)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v4 := range obj.PreviousEpochAttestations {
		_v0 += 4
		if _v4 == nil {
			_v4 = new(PendingAttestation)
		}
		_v0 += _v4.SizeSSZ()
	}
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v5 := range obj.CurrentEpochAttestations {
		_v0 += 4
		if _v5 == nil {
			_v5 = new(PendingAttestation)
		}
		_v0 += _v5.SizeSSZ()
	}
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v6 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v6)
	}
	for _, _v7 := range obj.Eth1DataVotes {
		if _v7 == nil {
			_v7 = new(Eth1Data)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v8 := range obj.Validators {
		if _v8 == nil {
			_v8 = new(Validator)
		}
		if err := _v8.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	_v9 := len(obj.PreviousEpochAttestations) * 4
	for _, _v10 := range obj.PreviousEpochAttestations {
		ssz.EncodeUint32(w, uint32(_v9))
		if _v10 == nil {
			_v10 = new(PendingAttestation)
		}
		_v9 += _v10.SizeSSZ()
	}
	for _, _v11 := range obj.PreviousEpochAttestations {
		if _v11 == nil {
			_v11 = new(PendingAttestation)
		}
		if err := _v11.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	_v12 := len(obj.CurrentEpochAttestations) * 4
	for _, _v13 := range obj.CurrentEpochAttestations {
		ssz.EncodeUint32(w, uint32(_v12))
		if _v13 == nil {
			_v13 = new(PendingAttestation)
		}
		_v12 += _v13.SizeSSZ()
	}
	for _, _v14 := range obj.CurrentEpochAttestations {
		if _v14 == nil {
			_v14 = new(PendingAttestation)
		}
		if err := _v14.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconState) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.GenesisTime = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.GenesisValidatorsRoot = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Slot = _v2
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint64(r)
	if _e5 != nil {
		return _e5
	}
	obj.Eth1DepositIndex = _v5
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	r, _v7, _e7 := ssz.DecodeUint32(r)
	if _e7 != nil {
		return _e7
	}
	r, _v8, _e8 := ssz.DecodeUint64s(r)
	if _e8 != nil {
		return _e8
	}
	obj.Slashings = _v8
	r, _v9, _e9 := ssz.DecodeUint32(r)
	if _e9 != nil {
		return _e9
	}
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.JustificationBits = _v11
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	_v12 := r[_v3:_v4]
	_v13 := r[_v3:_v4]
	_v14 := r[_v3:_v4]
	_v15 := r[_v3:_v4]
	_v15, _v16, _e12 := ssz.DecodeUint64s(_v15)
	if _e12 != nil {
		return _e12
	}
	obj.Balances = _v16
	_v17 := r[_v3:_v4]
	_v18 := r[_v3:_v4]
	return nil
}

func (obj *BeaconStateAltair) SizeSSZ() int {
	s := 2736629
	s += len(obj.HistoricalRoots) * 32
	s += len(obj.Eth1DataVotes) * 72
	s += len(obj.Validators) * 121
	s += len(obj.Balances) * 8
	s += len(obj.PreviousEpochParticipation)
	s += len(obj.CurrentEpochParticipation)
	s += len(obj.InactivityScores) * 8
	return s
}

func (obj *BeaconStateAltair) MarshalSSZTo(w []byte) error {
	_v0 := 2736629
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v1 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v1)
	}
	for _, _v2 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.HistoricalRoots) * 32
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Eth1DataVotes) * 72
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Validators) * 121
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Balances) * 8
	for _, _v3 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v3)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.PreviousEpochParticipation)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.CurrentEpochParticipation)
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v4 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v4)
	}
	for _, _v5 := range obj.Eth1DataVotes {
		if _v5 == nil {
			_v5 = new(Eth1Data)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v6 := range obj.Validators {
		if _v6 == nil {
			_v6 = new(Validator)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	return nil
}

func (obj *BeaconStateAltair) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.GenesisTime = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.GenesisValidatorsRoot = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Slot = _v2
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint64(r)
	if _e5 != nil {
		return _e5
	}
	obj.Eth1DepositIndex = _v5
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	r, _v7, _e7 := ssz.DecodeUint32(r)
	if _e7 != nil {
		return _e7
	}
	r, _v8, _e8 := ssz.DecodeUint64s(r)
	if _e8 != nil {
		return _e8
	}
	obj.Slashings = _v8
	r, _v9, _e9 := ssz.DecodeUint32(r)
	if _e9 != nil {
		return _e9
	}
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.JustificationBits = _v11
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v12, _e12 := ssz.DecodeUint32(r)
	if _e12 != nil {
		return _e12
	}
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	_v13 := r[_v3:_v4]
	_v14 := r[_v3:_v4]
	_v15 := r[_v3:_v4]
	_v16 := r[_v3:_v4]
	_v16, _v17, _e13 := ssz.DecodeUint64s(_v16)
	if _e13 != nil {
		return _e13
	}
	obj.Balances = _v17
	_v18 := r[_v3:_v4]
	_v18, _v19, _e14 := ssz.DecodeBytes(_v18)
	if _e14 != nil {
		return _e14
	}
	obj.PreviousEpochParticipation = _v19
	_v20 := r[_v3:_v4]
	_v20, _v21, _e15 := ssz.DecodeBytes(_v20)
	if _e15 != nil {
		return _e15
	}
	obj.CurrentEpochParticipation = _v21
	_v22 := r[_v3:_v4]
	_v22, _v23, _e16 := ssz.DecodeUint64s(_v22)
	if _e16 != nil {
		return _e16
	}
	obj.InactivityScores = _v23
	return nil
}

func (obj *BeaconStateBellatrix) SizeSSZ() int {
	s := 2736633
	s += len(obj.HistoricalRoots) * 32
	s += len(obj.Eth1DataVotes) * 72
	s += len(obj.Validators) * 121
	s += len(obj.Balances) * 8
	s += len(obj.PreviousEpochParticipation)
	s += len(obj.CurrentEpochParticipation)
	s += len(obj.InactivityScores) * 8
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	s += obj.LatestExecutionPayloadHeader.SizeSSZ()
	return s
}

func (obj *BeaconStateBellatrix) MarshalSSZTo(w []byte) error {
	_v0 := 2736633
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot)
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v1 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v1)
	}
	for _, _v2 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v2)
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.HistoricalRoots) * 32
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Eth1DataVotes) * 72
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Validators) * 121
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Balances) * 8
	for _, _v3 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v3)
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.PreviousEpochParticipation)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.CurrentEpochParticipation)
	ssz.EncodeBytes(w, obj.JustificationBits)
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	_v0 += obj.LatestExecutionPayloadHeader.SizeSSZ()
	for _, _v4 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v4)
	}
	for _, _v5 := range obj.Eth1DataVotes {
		if _v5 == nil {
			_v5 = new(Eth1Data)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v6 := range obj.Validators {
		if _v6 == nil {
			_v6 = new(Validator)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	if err := obj.LatestExecutionPayloadHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconStateBellatrix) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.GenesisTime = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.GenesisValidatorsRoot = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Slot = _v2
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint64(r)
	if _e5 != nil {
		return _e5
	}
	obj.Eth1DepositIndex = _v5
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	r, _v7, _e7 := ssz.DecodeUint32(r)
	if _e7 != nil {
		return _e7
	}
	r, _v8, _e8 := ssz.DecodeUint64s(r)
	if _e8 != nil {
		return _e8
	}
	obj.Slashings = _v8
	r, _v9, _e9 := ssz.DecodeUint32(r)
	if _e9 != nil {
		return _e9
	}
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.JustificationBits = _v11
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v12, _e12 := ssz.DecodeUint32(r)
	if _e12 != nil {
		return _e12
	}
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v13, _e13 := ssz.DecodeUint32(r)
	if _e13 != nil {
		return _e13
	}
	_v14 := r[_v3:_v4]
	_v15 := r[_v3:_v4]
	_v16 := r[_v3:_v4]
	_v17 := r[_v3:_v4]
	_v17, _v18, _e14 := ssz.DecodeUint64s(_v17)
	if _e14 != nil {
		return _e14
	}
	obj.Balances = _v18
	_v19 := r[_v3:_v4]
	_v19, _v20, _e15 := ssz.DecodeBytes(_v19)
	if _e15 != nil {
		return _e15
	}
	obj.PreviousEpochParticipation = _v20
	_v21 := r[_v3:_v4]
	_v21, _v22, _e16 := ssz.DecodeBytes(_v21)
	if _e16 != nil {
		return _e16
	}
	obj.CurrentEpochParticipation = _v22
	_v23 := r[_v3:_v4]
	_v23, _v24, _e17 := ssz.DecodeUint64s(_v23)
	if _e17 != nil {
		return _e17
	}
	obj.InactivityScores = _v24
	_v25 := r[_v3:_v4]
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeader)
	}
	if err := obj.LatestExecutionPayloadHeader.UnmarshalSSZ(_v25); err != nil {
		return err
	}
	return nil
}

func (obj *BeaconStateCapella) SizeSSZ() int {
	s := 2736653
	s += len(obj.HistoricalRoots) * 32
	s += len(obj.Eth1DataVotes) * 72
	s += len(obj.Validators) * 121
	s += len(obj.Balances) * 8
	s += len(obj.PreviousEpochParticipation)
	s += len(obj.CurrentEpochParticipation)
	s += len(obj.InactivityScores) * 8
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	s += obj.LatestExecutionPayloadHeader.SizeSSZ()
	s += len(obj.HistoricalSummaries) * 64
	return s
}

func (obj *BeaconStateCapella) MarshalSSZTo(w []byte) error {
	_v0 := 2736653
	ssz.EncodeUint64(w, obj.GenesisTime)
	ssz.EncodeBytes(w, obj.GenesisValidatorsRoot[:])
	ssz.EncodeUint64(w, obj.Slot)
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v1 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v1[:])
	}
	for _, _v2 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v2[:])
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.HistoricalRoots) * 32
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Eth1DataVotes) * 72
	ssz.EncodeUint64(w, obj.Eth1DepositIndex)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Validators) * 121
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Balances) * 8
	for _, _v3 := range obj.RandaoMixes {
		ssz.EncodeBytes(w, _v3[:])
	}
	ssz.EncodeUint64s(w, obj.Slashings)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.PreviousEpochParticipation)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.CurrentEpochParticipation)
	ssz.EncodeBytes(w, obj.JustificationBits[:])
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.InactivityScores) * 8
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	_v0 += obj.LatestExecutionPayloadHeader.SizeSSZ()
	ssz.EncodeUint64(w, obj.NextWithdrawalIndex)
	ssz.EncodeUint64(w, obj.NextWithdrawalValidatorIndex)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.HistoricalSummaries) * 64
	for _, _v4 := range obj.HistoricalRoots {
		ssz.EncodeBytes(w, _v4)
	}
	for _, _v5 := range obj.Eth1DataVotes {
		if _v5 == nil {
			_v5 = new(Eth1Data)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	for _, _v6 := range obj.Validators {
		if _v6 == nil {
			_v6 = new(Validator)
		}
		if err := _v6.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	ssz.EncodeUint64s(w, obj.Balances)
	ssz.EncodeBytes(w, obj.PreviousEpochParticipation)
	ssz.EncodeBytes(w, obj.CurrentEpochParticipation)
	ssz.EncodeUint64s(w, obj.InactivityScores)
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	if err := obj.LatestExecutionPayloadHeader.MarshalSSZTo(w); err != nil {
		return err
	}
	for _, _v7 := range obj.HistoricalSummaries {
		if _v7 == nil {
			_v7 = new(HistoricalSummary)
		}
		if err := _v7.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *BeaconStateCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.GenesisTime = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.GenesisValidatorsRoot = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Slot = _v2
	if obj.Fork == nil {
		obj.Fork = new(Fork)
	}
	if err := obj.Fork.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.LatestBlockHeader == nil {
		obj.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err := obj.LatestBlockHeader.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v3, _e3 := ssz.DecodeUint32(r)
	if _e3 != nil {
		return _e3
	}
	if obj.Eth1Data == nil {
		obj.Eth1Data = new(Eth1Data)
	}
	if err := obj.Eth1Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v4, _e4 := ssz.DecodeUint32(r)
	if _e4 != nil {
		return _e4
	}
	r, _v5, _e5 := ssz.DecodeUint64(r)
	if _e5 != nil {
		return _e5
	}
	obj.Eth1DepositIndex = _v5
	r, _v6, _e6 := ssz.DecodeUint32(r)
	if _e6 != nil {
		return _e6
	}
	r, _v7, _e7 := ssz.DecodeUint32(r)
	if _e7 != nil {
		return _e7
	}
	r, _v8, _e8 := ssz.DecodeUint64s(r)
	if _e8 != nil {
		return _e8
	}
	obj.Slashings = _v8
	r, _v9, _e9 := ssz.DecodeUint32(r)
	if _e9 != nil {
		return _e9
	}
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.JustificationBits = _v11
	if obj.PreviousJustifiedCheckpoint == nil {
		obj.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.PreviousJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.CurrentJustifiedCheckpoint == nil {
		obj.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err := obj.CurrentJustifiedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.FinalizedCheckpoint == nil {
		obj.FinalizedCheckpoint = new(Checkpoint)
	}
	if err := obj.FinalizedCheckpoint.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v12, _e12 := ssz.DecodeUint32(r)
	if _e12 != nil {
		return _e12
	}
	if obj.CurrentSyncCommittee == nil {
		obj.CurrentSyncCommittee = new(SyncCommittee)
	}
	if err := obj.CurrentSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.NextSyncCommittee == nil {
		obj.NextSyncCommittee = new(SyncCommittee)
	}
	if err := obj.NextSyncCommittee.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v13, _e13 := ssz.DecodeUint32(r)
	if _e13 != nil {
		return _e13
	}
	r, _v14, _e14 := ssz.DecodeUint64(r)
	if _e14 != nil {
		return _e14
	}
	obj.NextWithdrawalIndex = _v14
	r, _v15, _e15 := ssz.DecodeUint64(r)
	if _e15 != nil {
		return _e15
	}
	obj.NextWithdrawalValidatorIndex = _v15
	r, _v16, _e16 := ssz.DecodeUint32(r)
	if _e16 != nil {
		return _e16
	}
	_v17 := r[_v3:_v4]
	_v18 := r[_v3:_v4]
	_v19 := r[_v3:_v4]
	_v20 := r[_v3:_v4]
	_v20, _v21, _e17 := ssz.DecodeUint64s(_v20)
	if _e17 != nil {
		return _e17
	}
	obj.Balances = _v21
	_v22 := r[_v3:_v4]
	_v22, _v23, _e18 := ssz.DecodeBytes(_v22)
	if _e18 != nil {
		return _e18
	}
	obj.PreviousEpochParticipation = _v23
	_v24 := r[_v3:_v4]
	_v24, _v25, _e19 := ssz.DecodeBytes(_v24)
	if _e19 != nil {
		return _e19
	}
	obj.CurrentEpochParticipation = _v25
	_v26 := r[_v3:_v4]
	_v26, _v27, _e20 := ssz.DecodeUint64s(_v26)
	if _e20 != nil {
		return _e20
	}
	obj.InactivityScores = _v27
	_v28 := r[_v3:_v4]
	if obj.LatestExecutionPayloadHeader == nil {
		obj.LatestExecutionPayloadHeader = new(ExecutionPayloadHeaderCapella)
	}
	if err := obj.LatestExecutionPayloadHeader.UnmarshalSSZ(_v28); err != nil {
		return err
	}
	_v29 := r[_v3:_v4]
	return nil
}

func (obj *Checkpoint) SizeSSZ() int {
	s := 40
	return s
}

func (obj *Checkpoint) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Epoch)
	ssz.EncodeBytes(w, obj.Root)
	return nil
}

func (obj *Checkpoint) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Epoch = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Root = _v1
	return nil
}

func (obj *Deposit) SizeSSZ() int {
	s := 1240
	return s
}

func (obj *Deposit) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.Proof {
		ssz.EncodeBytes(w, _v0)
	}
	if obj.Data == nil {
		obj.Data = new(DepositData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *Deposit) UnmarshalSSZ(r []byte) error {
	if obj.Data == nil {
		obj.Data = new(DepositData)
	}
	if err := obj.Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	return nil
}

func (obj *DepositData) SizeSSZ() int {
	s := 184
	return s
}

func (obj *DepositData) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey[:])
	ssz.EncodeBytes(w, obj.WithdrawalCredentials[:])
	ssz.EncodeUint64(w, obj.Amount)
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *DepositData) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Pubkey = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.WithdrawalCredentials = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Amount = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.Signature = _v3
	return nil
}

func (obj *DepositMessage) SizeSSZ() int {
	s := 88
	return s
}

func (obj *DepositMessage) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.WithdrawalCredentials)
	ssz.EncodeUint64(w, obj.Amount)
	return nil
}

func (obj *DepositMessage) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Pubkey = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.WithdrawalCredentials = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Amount = _v2
	return nil
}

func (obj *ErrorResponse) SizeSSZ() int {
	s := 4
	s += len(obj.Message)
	return s
}

func (obj *ErrorResponse) MarshalSSZTo(w []byte) error {
	_v0 := 4
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Message)
	ssz.EncodeBytes(w, obj.Message)
	return nil
}

func (obj *ErrorResponse) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	_v1 := r[_v0:]
	_v1, _v2, _e1 := ssz.DecodeBytes(_v1)
	if _e1 != nil {
		return _e1
	}
	obj.Message = _v2
	return nil
}

func (obj *Eth1Block) SizeSSZ() int {
	s := 48
	return s
}

func (obj *Eth1Block) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeBytes(w, obj.DepositRoot)
	ssz.EncodeUint64(w, obj.DepositCount)
	return nil
}

func (obj *Eth1Block) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Timestamp = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.DepositRoot = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.DepositCount = _v2
	return nil
}

func (obj *Eth1Data) SizeSSZ() int {
	s := 72
	return s
}

func (obj *Eth1Data) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.DepositRoot)
	ssz.EncodeUint64(w, obj.DepositCount)
	ssz.EncodeBytes(w, obj.BlockHash)
	return nil
}

func (obj *Eth1Data) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.DepositRoot = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.DepositCount = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.BlockHash = _v2
	return nil
}

func (obj *ExecutionPayload) SizeSSZ() int {
	s := 508
	s += len(obj.ExtraData)
	for _, _v0 := range obj.Transactions {
		s += 4
		s += len(_v0)
	}
	return s
}

func (obj *ExecutionPayload) MarshalSSZTo(w []byte) error {
	_v0 := 508
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ExtraData)
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v1 := range obj.Transactions {
		_v0 += 4
		_v0 += len(_v1)
	}
	ssz.EncodeBytes(w, obj.ExtraData)
	_v2 := len(obj.Transactions) * 4
	for _, _v3 := range obj.Transactions {
		ssz.EncodeUint32(w, uint32(_v2))
		_v2 += len(_v3)
	}
	for _, _v4 := range obj.Transactions {
		ssz.EncodeBytes(w, _v4)
	}
	return nil
}

func (obj *ExecutionPayload) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.ParentHash = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.FeeRecipient = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.StateRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.ReceiptsRoot = _v3
	r, _v4, _e4 := ssz.DecodeBytes(r)
	if _e4 != nil {
		return _e4
	}
	obj.LogsBloom = _v4
	r, _v5, _e5 := ssz.DecodeBytes(r)
	if _e5 != nil {
		return _e5
	}
	obj.PrevRandao = _v5
	r, _v6, _e6 := ssz.DecodeUint64(r)
	if _e6 != nil {
		return _e6
	}
	obj.BlockNumber = _v6
	r, _v7, _e7 := ssz.DecodeUint64(r)
	if _e7 != nil {
		return _e7
	}
	obj.GasLimit = _v7
	r, _v8, _e8 := ssz.DecodeUint64(r)
	if _e8 != nil {
		return _e8
	}
	obj.GasUsed = _v8
	r, _v9, _e9 := ssz.DecodeUint64(r)
	if _e9 != nil {
		return _e9
	}
	obj.Timestamp = _v9
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.BaseFeePerGas = _v11
	r, _v12, _e12 := ssz.DecodeBytes(r)
	if _e12 != nil {
		return _e12
	}
	obj.BlockHash = _v12
	r, _v13, _e13 := ssz.DecodeUint32(r)
	if _e13 != nil {
		return _e13
	}
	_v14 := r[_v10:_v13]
	_v14, _v15, _e14 := ssz.DecodeBytes(_v14)
	if _e14 != nil {
		return _e14
	}
	obj.ExtraData = _v15
	_v16 := r[_v10:_v13]
	return nil
}

func (obj *ExecutionPayloadCapella) SizeSSZ() int {
	s := 512
	s += len(obj.ExtraData)
	for _, _v0 := range obj.Transactions {
		s += 4
		s += len(_v0)
	}
	s += len(obj.Withdrawals) * 44
	return s
}

func (obj *ExecutionPayloadCapella) MarshalSSZTo(w []byte) error {
	_v0 := 512
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ExtraData)
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeUint32(w, uint32(_v0))
	for _, _v1 := range obj.Transactions {
		_v0 += 4
		_v0 += len(_v1)
	}
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.Withdrawals) * 44
	ssz.EncodeBytes(w, obj.ExtraData)
	_v2 := len(obj.Transactions) * 4
	for _, _v3 := range obj.Transactions {
		ssz.EncodeUint32(w, uint32(_v2))
		_v2 += len(_v3)
	}
	for _, _v4 := range obj.Transactions {
		ssz.EncodeBytes(w, _v4)
	}
	for _, _v5 := range obj.Withdrawals {
		if _v5 == nil {
			_v5 = new(Withdrawal)
		}
		if err := _v5.MarshalSSZTo(w); err != nil {
			return err
		}
	}
	return nil
}

func (obj *ExecutionPayloadCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.ParentHash = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.FeeRecipient = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.StateRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.ReceiptsRoot = _v3
	r, _v4, _e4 := ssz.DecodeBytes(r)
	if _e4 != nil {
		return _e4
	}
	obj.LogsBloom = _v4
	r, _v5, _e5 := ssz.DecodeBytes(r)
	if _e5 != nil {
		return _e5
	}
	obj.PrevRandao = _v5
	r, _v6, _e6 := ssz.DecodeUint64(r)
	if _e6 != nil {
		return _e6
	}
	obj.BlockNumber = _v6
	r, _v7, _e7 := ssz.DecodeUint64(r)
	if _e7 != nil {
		return _e7
	}
	obj.GasLimit = _v7
	r, _v8, _e8 := ssz.DecodeUint64(r)
	if _e8 != nil {
		return _e8
	}
	obj.GasUsed = _v8
	r, _v9, _e9 := ssz.DecodeUint64(r)
	if _e9 != nil {
		return _e9
	}
	obj.Timestamp = _v9
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.BaseFeePerGas = _v11
	r, _v12, _e12 := ssz.DecodeBytes(r)
	if _e12 != nil {
		return _e12
	}
	obj.BlockHash = _v12
	r, _v13, _e13 := ssz.DecodeUint32(r)
	if _e13 != nil {
		return _e13
	}
	r, _v14, _e14 := ssz.DecodeUint32(r)
	if _e14 != nil {
		return _e14
	}
	_v15 := r[_v10:_v13]
	_v15, _v16, _e15 := ssz.DecodeBytes(_v15)
	if _e15 != nil {
		return _e15
	}
	obj.ExtraData = _v16
	_v17 := r[_v10:_v13]
	_v18 := r[_v10:_v13]
	return nil
}

func (obj *ExecutionPayloadHeader) SizeSSZ() int {
	s := 536
	s += len(obj.ExtraData)
	return s
}

func (obj *ExecutionPayloadHeader) MarshalSSZTo(w []byte) error {
	_v0 := 536
	ssz.EncodeBytes(w, obj.ParentHash)
	ssz.EncodeBytes(w, obj.FeeRecipient)
	ssz.EncodeBytes(w, obj.StateRoot)
	ssz.EncodeBytes(w, obj.ReceiptsRoot)
	ssz.EncodeBytes(w, obj.LogsBloom)
	ssz.EncodeBytes(w, obj.PrevRandao)
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ExtraData)
	ssz.EncodeBytes(w, obj.BaseFeePerGas)
	ssz.EncodeBytes(w, obj.BlockHash)
	ssz.EncodeBytes(w, obj.TransactionsRoot)
	ssz.EncodeBytes(w, obj.ExtraData)
	return nil
}

func (obj *ExecutionPayloadHeader) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.ParentHash = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.FeeRecipient = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.StateRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.ReceiptsRoot = _v3
	r, _v4, _e4 := ssz.DecodeBytes(r)
	if _e4 != nil {
		return _e4
	}
	obj.LogsBloom = _v4
	r, _v5, _e5 := ssz.DecodeBytes(r)
	if _e5 != nil {
		return _e5
	}
	obj.PrevRandao = _v5
	r, _v6, _e6 := ssz.DecodeUint64(r)
	if _e6 != nil {
		return _e6
	}
	obj.BlockNumber = _v6
	r, _v7, _e7 := ssz.DecodeUint64(r)
	if _e7 != nil {
		return _e7
	}
	obj.GasLimit = _v7
	r, _v8, _e8 := ssz.DecodeUint64(r)
	if _e8 != nil {
		return _e8
	}
	obj.GasUsed = _v8
	r, _v9, _e9 := ssz.DecodeUint64(r)
	if _e9 != nil {
		return _e9
	}
	obj.Timestamp = _v9
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.BaseFeePerGas = _v11
	r, _v12, _e12 := ssz.DecodeBytes(r)
	if _e12 != nil {
		return _e12
	}
	obj.BlockHash = _v12
	r, _v13, _e13 := ssz.DecodeBytes(r)
	if _e13 != nil {
		return _e13
	}
	obj.TransactionsRoot = _v13
	_v14 := r[_v10:]
	_v14, _v15, _e14 := ssz.DecodeBytes(_v14)
	if _e14 != nil {
		return _e14
	}
	obj.ExtraData = _v15
	return nil
}

func (obj *ExecutionPayloadHeaderCapella) SizeSSZ() int {
	s := 568
	s += len(obj.ExtraData)
	return s
}

func (obj *ExecutionPayloadHeaderCapella) MarshalSSZTo(w []byte) error {
	_v0 := 568
	ssz.EncodeBytes(w, obj.ParentHash[:])
	ssz.EncodeBytes(w, obj.FeeRecipient[:])
	ssz.EncodeBytes(w, obj.StateRoot[:])
	ssz.EncodeBytes(w, obj.ReceiptsRoot[:])
	ssz.EncodeBytes(w, obj.LogsBloom[:])
	ssz.EncodeBytes(w, obj.PrevRandao[:])
	ssz.EncodeUint64(w, obj.BlockNumber)
	ssz.EncodeUint64(w, obj.GasLimit)
	ssz.EncodeUint64(w, obj.GasUsed)
	ssz.EncodeUint64(w, obj.Timestamp)
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.ExtraData)
	ssz.EncodeBytes(w, obj.BaseFeePerGas[:])
	ssz.EncodeBytes(w, obj.BlockHash[:])
	ssz.EncodeBytes(w, obj.TransactionsRoot[:])
	ssz.EncodeBytes(w, obj.WithdrawalRoot[:])
	ssz.EncodeBytes(w, obj.ExtraData)
	return nil
}

func (obj *ExecutionPayloadHeaderCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.ParentHash = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.FeeRecipient = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.StateRoot = _v2
	r, _v3, _e3 := ssz.DecodeBytes(r)
	if _e3 != nil {
		return _e3
	}
	obj.ReceiptsRoot = _v3
	r, _v4, _e4 := ssz.DecodeBytes(r)
	if _e4 != nil {
		return _e4
	}
	obj.LogsBloom = _v4
	r, _v5, _e5 := ssz.DecodeBytes(r)
	if _e5 != nil {
		return _e5
	}
	obj.PrevRandao = _v5
	r, _v6, _e6 := ssz.DecodeUint64(r)
	if _e6 != nil {
		return _e6
	}
	obj.BlockNumber = _v6
	r, _v7, _e7 := ssz.DecodeUint64(r)
	if _e7 != nil {
		return _e7
	}
	obj.GasLimit = _v7
	r, _v8, _e8 := ssz.DecodeUint64(r)
	if _e8 != nil {
		return _e8
	}
	obj.GasUsed = _v8
	r, _v9, _e9 := ssz.DecodeUint64(r)
	if _e9 != nil {
		return _e9
	}
	obj.Timestamp = _v9
	r, _v10, _e10 := ssz.DecodeUint32(r)
	if _e10 != nil {
		return _e10
	}
	r, _v11, _e11 := ssz.DecodeBytes(r)
	if _e11 != nil {
		return _e11
	}
	obj.BaseFeePerGas = _v11
	r, _v12, _e12 := ssz.DecodeBytes(r)
	if _e12 != nil {
		return _e12
	}
	obj.BlockHash = _v12
	r, _v13, _e13 := ssz.DecodeBytes(r)
	if _e13 != nil {
		return _e13
	}
	obj.TransactionsRoot = _v13
	r, _v14, _e14 := ssz.DecodeBytes(r)
	if _e14 != nil {
		return _e14
	}
	obj.WithdrawalRoot = _v14
	_v15 := r[_v10:]
	_v15, _v16, _e15 := ssz.DecodeBytes(_v15)
	if _e15 != nil {
		return _e15
	}
	obj.ExtraData = _v16
	return nil
}

func (obj *Fork) SizeSSZ() int {
	s := 16
	return s
}

func (obj *Fork) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.PreviousVersion)
	ssz.EncodeBytes(w, obj.CurrentVersion)
	ssz.EncodeUint64(w, obj.Epoch)
	return nil
}

func (obj *Fork) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.PreviousVersion = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.CurrentVersion = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Epoch = _v2
	return nil
}

func (obj *HistoricalBatch) SizeSSZ() int {
	s := 524288
	return s
}

func (obj *HistoricalBatch) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.BlockRoots {
		ssz.EncodeBytes(w, _v0[:])
	}
	for _, _v1 := range obj.StateRoots {
		ssz.EncodeBytes(w, _v1[:])
	}
	return nil
}

func (obj *HistoricalBatch) UnmarshalSSZ(r []byte) error {
	return nil
}

func (obj *HistoricalSummary) SizeSSZ() int {
	s := 64
	return s
}

func (obj *HistoricalSummary) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.BlockSummaryRoot[:])
	ssz.EncodeBytes(w, obj.StateSummaryRoot[:])
	return nil
}

func (obj *HistoricalSummary) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.BlockSummaryRoot = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.StateSummaryRoot = _v1
	return nil
}

func (obj *IndexedAttestation) SizeSSZ() int {
	s := 228
	s += len(obj.AttestationIndices) * 8
	return s
}

func (obj *IndexedAttestation) MarshalSSZTo(w []byte) error {
	_v0 := 228
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.AttestationIndices) * 8
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature)
	ssz.EncodeUint64s(w, obj.AttestationIndices)
	return nil
}

func (obj *IndexedAttestation) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Signature = _v1
	_v2 := r[_v0:]
	_v2, _v3, _e2 := ssz.DecodeUint64s(_v2)
	if _e2 != nil {
		return _e2
	}
	obj.AttestationIndices = _v3
	return nil
}

func (obj *PendingAttestation) SizeSSZ() int {
	s := 148
	s += len(obj.AggregationBits)
	return s
}

func (obj *PendingAttestation) MarshalSSZTo(w []byte) error {
	_v0 := 148
	ssz.EncodeUint32(w, uint32(_v0))
	_v0 += len(obj.AggregationBits)
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeUint64(w, obj.InclusionDelay)
	ssz.EncodeUint64(w, obj.ProposerIndex)
	ssz.EncodeBytes(w, obj.AggregationBits)
	return nil
}

func (obj *PendingAttestation) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	if obj.Data == nil {
		obj.Data = new(AttestationData)
	}
	if err := obj.Data.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.InclusionDelay = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.ProposerIndex = _v2
	_v3 := r[_v0:]
	_v3, _v4, _e3 := ssz.DecodeBytes(_v3)
	if _e3 != nil {
		return _e3
	}
	obj.AggregationBits = _v4
	return nil
}

func (obj *ProposerSlashing) SizeSSZ() int {
	s := 416
	return s
}

func (obj *ProposerSlashing) MarshalSSZTo(w []byte) error {
	if obj.Header1 == nil {
		obj.Header1 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header1.MarshalSSZTo(w); err != nil {
		return err
	}
	if obj.Header2 == nil {
		obj.Header2 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header2.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *ProposerSlashing) UnmarshalSSZ(r []byte) error {
	if obj.Header1 == nil {
		obj.Header1 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header1.UnmarshalSSZ(r); err != nil {
		return err
	}
	if obj.Header2 == nil {
		obj.Header2 = new(SignedBeaconBlockHeader)
	}
	if err := obj.Header2.UnmarshalSSZ(r); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBLSToExecutionChange) SizeSSZ() int {
	s := 172
	return s
}

func (obj *SignedBLSToExecutionChange) MarshalSSZTo(w []byte) error {
	if obj.Message == nil {
		obj.Message = new(BLSToExecutionChange)
	}
	if err := obj.Message.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	return nil
}

func (obj *SignedBLSToExecutionChange) UnmarshalSSZ(r []byte) error {
	if obj.Message == nil {
		obj.Message = new(BLSToExecutionChange)
	}
	if err := obj.Message.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Signature = _v0
	return nil
}

func (obj *SignedBeaconBlock) SizeSSZ() int {
	s := 100
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	s += obj.Block.SizeSSZ()
	return s
}

func (obj *SignedBeaconBlock) MarshalSSZTo(w []byte) error {
	_v0 := 100
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	_v0 += obj.Block.SizeSSZ()
	ssz.EncodeBytes(w, obj.Signature)
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	if err := obj.Block.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlock) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Signature = _v1
	_v2 := r[_v0:]
	if obj.Block == nil {
		obj.Block = new(BeaconBlock)
	}
	if err := obj.Block.UnmarshalSSZ(_v2); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlockCapella) SizeSSZ() int {
	s := 100
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	s += obj.Block.SizeSSZ()
	return s
}

func (obj *SignedBeaconBlockCapella) MarshalSSZTo(w []byte) error {
	_v0 := 100
	ssz.EncodeUint32(w, uint32(_v0))
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	_v0 += obj.Block.SizeSSZ()
	ssz.EncodeBytes(w, obj.Signature)
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	if err := obj.Block.MarshalSSZTo(w); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlockCapella) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint32(r)
	if _e0 != nil {
		return _e0
	}
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Signature = _v1
	_v2 := r[_v0:]
	if obj.Block == nil {
		obj.Block = new(BeaconBlockCapella)
	}
	if err := obj.Block.UnmarshalSSZ(_v2); err != nil {
		return err
	}
	return nil
}

func (obj *SignedBeaconBlockHeader) SizeSSZ() int {
	s := 208
	return s
}

func (obj *SignedBeaconBlockHeader) MarshalSSZTo(w []byte) error {
	if obj.Header == nil {
		obj.Header = new(BeaconBlockHeader)
	}
	if err := obj.Header.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *SignedBeaconBlockHeader) UnmarshalSSZ(r []byte) error {
	if obj.Header == nil {
		obj.Header = new(BeaconBlockHeader)
	}
	if err := obj.Header.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Signature = _v0
	return nil
}

func (obj *SignedVoluntaryExit) SizeSSZ() int {
	s := 112
	return s
}

func (obj *SignedVoluntaryExit) MarshalSSZTo(w []byte) error {
	if obj.Exit == nil {
		obj.Exit = new(VoluntaryExit)
	}
	if err := obj.Exit.MarshalSSZTo(w); err != nil {
		return err
	}
	ssz.EncodeBytes(w, obj.Signature[:])
	return nil
}

func (obj *SignedVoluntaryExit) UnmarshalSSZ(r []byte) error {
	if obj.Exit == nil {
		obj.Exit = new(VoluntaryExit)
	}
	if err := obj.Exit.UnmarshalSSZ(r); err != nil {
		return err
	}
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Signature = _v0
	return nil
}

func (obj *SigningRoot) SizeSSZ() int {
	s := 40
	return s
}

func (obj *SigningRoot) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.ObjectRoot)
	ssz.EncodeBytes(w, obj.Domain)
	return nil
}

func (obj *SigningRoot) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.ObjectRoot = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.Domain = _v1
	return nil
}

func (obj *SyncAggregate) SizeSSZ() int {
	s := 160
	return s
}

func (obj *SyncAggregate) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.SyncCommiteeBits)
	ssz.EncodeBytes(w, obj.SyncCommiteeSignature[:])
	return nil
}

func (obj *SyncAggregate) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.SyncCommiteeBits = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.SyncCommiteeSignature = _v1
	return nil
}

func (obj *SyncCommittee) SizeSSZ() int {
	s := 24624
	return s
}

func (obj *SyncCommittee) MarshalSSZTo(w []byte) error {
	for _, _v0 := range obj.PubKeys {
		ssz.EncodeBytes(w, _v0)
	}
	ssz.EncodeBytes(w, obj.AggregatePubKey[:])
	return nil
}

func (obj *SyncCommittee) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.AggregatePubKey = _v0
	return nil
}

func (obj *Transfer) SizeSSZ() int {
	s := 184
	return s
}

func (obj *Transfer) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Sender)
	ssz.EncodeUint64(w, obj.Recipient)
	ssz.EncodeUint64(w, obj.Amount)
	ssz.EncodeUint64(w, obj.Fee)
	ssz.EncodeUint64(w, obj.Slot)
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.Signature)
	return nil
}

func (obj *Transfer) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Sender = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.Recipient = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.Amount = _v2
	r, _v3, _e3 := ssz.DecodeUint64(r)
	if _e3 != nil {
		return _e3
	}
	obj.Fee = _v3
	r, _v4, _e4 := ssz.DecodeUint64(r)
	if _e4 != nil {
		return _e4
	}
	obj.Slot = _v4
	r, _v5, _e5 := ssz.DecodeBytes(r)
	if _e5 != nil {
		return _e5
	}
	obj.Pubkey = _v5
	r, _v6, _e6 := ssz.DecodeBytes(r)
	if _e6 != nil {
		return _e6
	}
	obj.Signature = _v6
	return nil
}

func (obj *Validator) SizeSSZ() int {
	s := 121
	return s
}

func (obj *Validator) MarshalSSZTo(w []byte) error {
	ssz.EncodeBytes(w, obj.Pubkey)
	ssz.EncodeBytes(w, obj.WithdrawalCredentials)
	ssz.EncodeUint64(w, obj.EffectiveBalance)
	ssz.EncodeBool(w, bool(obj.Slashed))
	ssz.EncodeUint64(w, obj.ActivationEligibilityEpoch)
	ssz.EncodeUint64(w, obj.ActivationEpoch)
	ssz.EncodeUint64(w, obj.ExitEpoch)
	ssz.EncodeUint64(w, obj.WithdrawableEpoch)
	return nil
}

func (obj *Validator) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeBytes(r)
	if _e0 != nil {
		return _e0
	}
	obj.Pubkey = _v0
	r, _v1, _e1 := ssz.DecodeBytes(r)
	if _e1 != nil {
		return _e1
	}
	obj.WithdrawalCredentials = _v1
	r, _v2, _e2 := ssz.DecodeUint64(r)
	if _e2 != nil {
		return _e2
	}
	obj.EffectiveBalance = _v2
	r, _v3, _e3 := ssz.DecodeBool(r)
	if _e3 != nil {
		return _e3
	}
	obj.Slashed = SlashedT(_v3)
	r, _v4, _e4 := ssz.DecodeUint64(r)
	if _e4 != nil {
		return _e4
	}
	obj.ActivationEligibilityEpoch = _v4
	r, _v5, _e5 := ssz.DecodeUint64(r)
	if _e5 != nil {
		return _e5
	}
	obj.ActivationEpoch = _v5
	r, _v6, _e6 := ssz.DecodeUint64(r)
	if _e6 != nil {
		return _e6
	}
	obj.ExitEpoch = _v6
	r, _v7, _e7 := ssz.DecodeUint64(r)
	if _e7 != nil {
		return _e7
	}
	obj.WithdrawableEpoch = _v7
	return nil
}

func (obj *VoluntaryExit) SizeSSZ() int {
	s := 16
	return s
}

func (obj *VoluntaryExit) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Epoch)
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	return nil
}

func (obj *VoluntaryExit) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Epoch = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.ValidatorIndex = _v1
	return nil
}

func (obj *Withdrawal) SizeSSZ() int {
	s := 44
	return s
}

func (obj *Withdrawal) MarshalSSZTo(w []byte) error {
	ssz.EncodeUint64(w, obj.Index)
	ssz.EncodeUint64(w, obj.ValidatorIndex)
	ssz.EncodeBytes(w, obj.Address[:])
	ssz.EncodeUint64(w, obj.Amount)
	return nil
}

func (obj *Withdrawal) UnmarshalSSZ(r []byte) error {
	r, _v0, _e0 := ssz.DecodeUint64(r)
	if _e0 != nil {
		return _e0
	}
	obj.Index = _v0
	r, _v1, _e1 := ssz.DecodeUint64(r)
	if _e1 != nil {
		return _e1
	}
	obj.ValidatorIndex = _v1
	r, _v2, _e2 := ssz.DecodeBytes(r)
	if _e2 != nil {
		return _e2
	}
	obj.Address = _v2
	r, _v3, _e3 := ssz.DecodeUint64(r)
	if _e3 != nil {
		return _e3
	}
	obj.Amount = _v3
	return nil
}
